---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512
    cpus: 3

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04

suites:
  - name: pkg_net
    run_list:
      - recipe[chef-mesos::default]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg

  - name: pkg_local
    run_list:
      - recipe[chef-mesos::default]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg_local
          resolve: true

  - name: pkg_net_force
    run_list:
      - recipe[chef-mesos::default]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg
          force: true

  - name: pkg_local_force
    run_list:
      - recipe[chef-mesos::default]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg_local
          force: true
          resolve: true


