---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04

suites:
  - name: pkg_net
    driver_config:
      customize:
        memory: 512
        cpuexecutioncap: 50

    run_list:
      - recipe[chef-mesos::default]
      - recipe[chef-mesos::templates]
      - recipe[chef-mesos::start_services]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg

  # - name: pkg_local
  #   driver_config:
  #     customize:
  #       memory: 512
  #       cpuexecutioncap: 50

  #   run_list:
  #     - recipe[chef-mesos::default]
  #     - recipe[chef-mesos::templates]
  #     - recipe[chef-mesos::start_services]
  #   attributes:
  #     mesos:
  #       install:
  #         mode: local
  #         via: pkg_local
  #         resolve: true

  - name: pkg_net_force
    driver_config:
      customize:
        memory: 512
        cpuexecutioncap: 50

    run_list:
      - recipe[chef-mesos::default]
      - recipe[chef-mesos::templates]
      - recipe[chef-mesos::start_services]
    attributes:
      mesos:
        install:
          mode: local
          via: pkg
          force: true

  # - name: pkg_local_force
  #   driver_config:
  #     customize:
  #       memory: 512
  #       cpuexecutioncap: 50

  #   run_list:
  #     - recipe[chef-mesos::default]
  #     - recipe[chef-mesos::templates]
  #     - recipe[chef-mesos::start_services]
  #   attributes:
  #     mesos:
  #       install:
  #         mode: local
  #         via: pkg_local
  #         force: true
  #         resolve: true


