Vagrant.configure("2") do |c|
  c.vm.box = "ubuntu-12.04"
  c.vm.box_url = "/Users/jason/programming/github/collective/base_boxes/precise64.box"
  c.vm.hostname = "default-ubuntu-1204.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "512"]
  end
end
