Vagrant.configure("2") do |c|
  c.vm.box = "opscode-testkitchen-ubuntu12"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_testkitchen-ubuntu12_provisionerless.box"
  c.vm.hostname = "default-testkitchen-ubuntu12.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "256"]
  end
end
